"""add tool timings

Revision ID: 233c09650a83
Revises: b616ae3fac8c
Create Date: 2026-08-09 19:21:36.852536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233c09650a83'
down_revision: Union[str, Sequence[str], None] = 'b616ae3fac8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_timings',
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index('ix_tool_timings_thread_id', 'tool_timings', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_timings_thread_id', table_name='tool_timings')
    op.drop_table('tool_timings')
    # ### end Alembic commands ###
