"""add jobs and job_events

Revision ID: 8aa642582b46
Revises: f9a10b37e3c4
Create Date: 2026-08-08 11:36:34.580103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa642582b46'
down_revision: Union[str, Sequence[str], None] = 'f9a10b37e3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'seq', name='uq_job_events_job_seq')
    )
    op.create_index('ix_job_events_job_id', 'job_events', ['job_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('step_budget', sa.Integer(), nullable=False),
    sa.Column('wall_clock_budget_s', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.Text(), nullable=False),
    sa.Column('last_event_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_index('ix_job_events_job_id', table_name='job_events')
    op.drop_table('job_events')
    # ### end Alembic commands ###
