"""add user schedules

Revision ID: b616ae3fac8c
Revises: e070f0c844c8
Create Date: 2026-08-08 15:48:33.407683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b616ae3fac8c'
down_revision: Union[str, Sequence[str], None] = 'e070f0c844c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('at_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_s', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_schedules_next_fire_at', 'user_schedules', ['next_fire_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_schedules_next_fire_at', table_name='user_schedules')
    op.drop_table('user_schedules')
    # ### end Alembic commands ###
