"""add thread title and archive

Revision ID: dd09f3e2a779
Revises: 5aaf8f13267a
Create Date: 2026-08-08 09:06:31.010257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd09f3e2a779'
down_revision: Union[str, Sequence[str], None] = '5aaf8f13267a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('title', sa.String(length=80), nullable=True))
    op.add_column('threads', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'archived_at')
    op.drop_column('threads', 'title')
    # ### end Alembic commands ###
