"""add memory forget and tool usage columns

Revision ID: f9a10b37e3c4
Revises: dd09f3e2a779
Create Date: 2026-08-08 10:11:13.475683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a10b37e3c4'
down_revision: Union[str, Sequence[str], None] = 'dd09f3e2a779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_tools', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dynamic_tools', sa.Column('last_outcome', sa.String(length=16), nullable=True))
    op.add_column('memory_items', sa.Column('forgotten_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_items', 'forgotten_at')
    op.drop_column('dynamic_tools', 'last_outcome')
    op.drop_column('dynamic_tools', 'last_used_at')
    # ### end Alembic commands ###
